import moment from 'moment-timezone';

const data = [
  {
    key: '1',
    type: 'test',
    place: '',
    name: 'Тест как учиться в RSSchool',
    organizer: 'dzmitry-varabei',
    comment: '4 часа на прохождение',
    done: false,
    hided: false,
    dateTime: moment({
      day: 10, year: 2020, month: 8, hour: 18, minute: 0,
    }),
  },
  {
    key: '2',
    type: 'stream',
    place: '',
    name: 'Git Basics. Live coding',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 19, year: 2020, month: 8, hour: 19, minute: 0,
    }),
  },
  {
    key: '3',
    type: 'start',
    place: '',
    name: 'Task 1. Calculator',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 21, year: 2020, month: 8, hour: 12, minute: 0,
    }),
  },
  {
    key: '4',
    type: 'start',
    place: '',
    name: 'Алгоритмические задания Stage#1. Part #1',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 22, year: 2020, month: 8, hour: 12, minute: 0,
    }),
  },
  {
    key: '5',
    type: 'self-education',
    place: '',
    name: 'JavaScript Intro',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({ day: 22, year: 2020, month: 8 }),
  },
  {
    key: '6',
    type: 'stream',
    place: '',
    name: 'FAQ: Photoshop and Figma',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 22, year: 2020, month: 8, hour: 20, minute: 0,
    }),
  },
  {
    key: '7',
    type: 'self-education',
    place: '',
    name: 'Flexbox and Grid',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({ day: 22, year: 2020, month: 8 }),
  },
  {
    key: '8',
    type: 'self-education',
    place: '',
    name: 'Ответы на вопросы по алгоритмическим заданиям Stage#1. Part #1',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({ day: 24, year: 2020, month: 8 }),
  },
  {
    key: '9',
    type: 'faculty',
    place: '',
    name: 'Live coding макета',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 25, year: 2020, month: 8, hour: 19, minute: 0,
    }),
  },
  {
    key: '10',
    type: 'test',
    place: '',
    name: 'Тест по основам Git.',
    organizer: 'dzmitry-varabei',
    comment: 'Ссылка будет в Discord. Его необходимо пройти за 24 часа',
    done: false,
    hided: false,
    dateTime: moment({
      day: 26, year: 2020, month: 8, hour: 18, minute: 0,
    }),
  },
  {
    key: '11',
    type: 'self-education',
    place: '',
    name: 'Evening Talk: Algorithms bootstrap',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({ day: 28, year: 2020, month: 8 }),
  },
  {
    key: '12',
    type: 'start',
    place: '',
    name: 'Task 2. Dynamic Landing Page',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 28, year: 2020, month: 8, hour: 12, minute: 0,
    }),
  },
  {
    key: '13',
    type: 'start',
    place: '',
    name: 'Singolo. Part 2 (tags, 4 and 3 columns layout)',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 29, year: 2020, month: 8, hour: 12, minute: 0,
    }),
  },
  {
    key: '14',
    type: 'self-education',
    place: '',
    name: 'JS Data Types',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hided: false,
    dateTime: moment({
      day: 26, year: 2020, month: 8, hour: 18, minute: 0,
    }),
  },
];

export default data;
