import { IEvent } from '../interfaces';

const loadingData: IEvent[] = [
  {
    id: '1',
    date: [2020, 8, 19],
    time: { hour: 18, minute: 0 },
    type: 'test',
    place: '',
    name: 'Тест как учиться в RSSchool',
    organizer: 'dzmitry-varabei',
    comment: '4 часа на прохождение',
    done: false,
    hidden: false,
  },
  {
    id: '2',
    date: [2020, 8, 19],
    time: { hour: 19, minute: 0 },
    type: 'stream',
    place: '',
    name: 'Git Basics. Live coding',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '3',
    date: [2020, 8, 21],
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Task 1. Calculator',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '4',
    date: [2020, 8, 22],
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Алгоритмические задания Stage#1. Part #1',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '5',
    date: [2020, 8, 22],
    time: null,
    type: 'self-education',
    place: '',
    name: 'JavaScript Intro',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '6',
    date: [2020, 8, 22],
    time: { hour: 20, minute: 0 },
    type: 'stream',
    place: '',
    name: 'FAQ: Photoshop and Figma',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '7',
    date: [2020, 8, 22],
    time: null,
    type: 'self-education',
    place: '',
    name: 'Flexbox and Grid',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '8',
    date: [2020, 8, 24],
    time: null,
    type: 'self-education',
    place: '',
    name: 'Ответы на вопросы по алгоритмическим заданиям Stage#1. Part #1',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '9',
    date: [2020, 8, 25],
    time: { hour: 19, minute: 0 },
    type: 'faculty',
    place: '',
    name: 'Live coding макета',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '10',
    date: [2020, 8, 26],
    time: { hour: 18, minute: 0 },
    type: 'test',
    place: '',
    name: 'Тест по основам Git.',
    organizer: 'dzmitry-varabei',
    comment: 'Ссылка будет в Discord. Его необходимо пройти за 24 часа',
    done: false,
    hidden: false,
  },
  {
    id: '11',
    date: [2020, 8, 28],
    time: null,
    type: 'self-education',
    place: '',
    name: 'Evening Talk: Algorithms bootstrap',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '12',
    date: [2020, 8, 28],
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Task 2. Dynamic Landing Page',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '13',
    date: [2020, 8, 29],
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Singolo. Part 2 (tags, 4 and 3 columns layout)',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    id: '14',
    date: [2020, 8, 26],
    time: { hour: 18, minute: 0 },
    type: 'self-education',
    place: '',
    name: 'JS Data Types',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
];

export default loadingData;
