import { IEvent } from '../interfaces';

const loadingData: IEvent[] = [
  {
    key: '1',
    date: { year: 2020, month: 8, day: 19 },
    time: { hour: 18, minute: 0 },
    type: 'test',
    place: '',
    name: 'Тест как учиться в RSSchool',
    organizer: 'dzmitry-varabei',
    comment: '4 часа на прохождение',
    done: false,
    hidden: false,
  },
  {
    key: '2',
    date: { year: 2020, month: 8, day: 19 },
    time: { hour: 19, minute: 0 },
    type: 'stream',
    place: '',
    name: 'Git Basics. Live coding',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '3',
    date: { year: 2020, month: 8, day: 21 },
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Task 1. Calculator',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '4',
    date: { year: 2020, month: 8, day: 22 },
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Алгоритмические задания Stage#1. Part #1',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '5',
    date: { year: 2020, month: 8, day: 22 },
    time: { hour: 12, minute: 0 },
    type: 'self-education',
    place: '',
    name: 'JavaScript Intro',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '6',
    date: { year: 2020, month: 8, day: 22 },
    time: { hour: 20, minute: 0 },
    type: 'stream',
    place: '',
    name: 'FAQ: Photoshop and Figma',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '7',
    date: { year: 2020, month: 8, day: 22 },
    time: { hour: 12, minute: 0 },
    type: 'self-education',
    place: '',
    name: 'Flexbox and Grid',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '8',
    date: { year: 2020, month: 8, day: 24 },
    time: { hour: 12, minute: 0 },
    type: 'self-education',
    place: '',
    name: 'Ответы на вопросы по алгоритмическим заданиям Stage#1. Part #1',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '9',
    date: { year: 2020, month: 8, day: 25 },
    time: { hour: 19, minute: 0 },
    type: 'faculty',
    place: '',
    name: 'Live coding макета',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '10',
    date: { year: 2020, month: 8, day: 26 },
    time: { hour: 18, minute: 0 },
    type: 'test',
    place: '',
    name: 'Тест по основам Git.',
    organizer: 'dzmitry-varabei',
    comment: 'Ссылка будет в Discord. Его необходимо пройти за 24 часа',
    done: false,
    hidden: false,
  },
  {
    key: '11',
    date: { year: 2020, month: 8, day: 28 },
    time: { hour: 12, minute: 0 },
    type: 'self-education',
    place: '',
    name: 'Evening Talk: Algorithms bootstrap',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '12',
    date: { year: 2020, month: 8, day: 28 },
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Task 2. Dynamic Landing Page',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '13',
    date: { year: 2020, month: 8, day: 29 },
    time: { hour: 12, minute: 0 },
    type: 'start',
    place: '',
    name: 'Singolo. Part 2 (tags, 4 and 3 columns layout)',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
  {
    key: '14',
    date: { year: 2020, month: 8, day: 26 },
    time: { hour: 18, minute: 0 },
    type: 'self-education',
    place: '',
    name: 'JS Data Types',
    organizer: 'dzmitry-varabei',
    comment: '',
    done: false,
    hidden: false,
  },
];

export default loadingData;
